# Introduction to deep learning and Pytorch*
<hr>

Deep learning refers to the use of multi-layered neural networks, a field significantly advanced by Geoffrey Hinton, who was awarded the Nobel Prize in Physics in 2024 for his foundational contributions.

![Hinton](./pics/hinton.jpg)

Deep learning is widely applied in both research and everyday life, including computer vision (CV), such as facial recognition and autonomous driving; natural language processing (NLP), such as machine translation and chatbots; time series forecasting, such as demand forecasting and financial risk prediction; speech recognition, such as digital assistant Siri; Bioinformatics, such as gene and protein expression, etc.  

```{mermaid}
flowchart TD
    A(Deep Learning) --> B("Computer Vision (CV)")
    A --> C("Natrual Language Processing (NLP)")
    A --> D(Time Series Forecasting)
    A --> E(Speech Recognition)
    A --> F(Bioinfomatics)
    A --> G(...)

```

Pytorch is an open-sourced deep learning libarary originally developed by Meta. It provides a high level API that helps building deep learing algorithms and architectures easily.
- Think of its high-level API as a set of "ready-to-use building blocks" —— it hides the messy details so you can focus on easily designing and assembling powerful AI models.

Other major deep learning libraries include:

- TensorFlow (Google’s industry-standard for large-scale production).
- JAX (Google's high-performance framework designed for cutting-edge numerical computing)
- MXNet (Amazon).
- ...

## Tensor

In deep learning, tensors are the fundamental building blocks of data. As multidimensional arrays of numbers, they generalize scalars, vectors, and matrices. 

- 0D Tensor: a scalar (a single number, like 5).

- 1D Tensor: a vector (a list of numbers, like [1, 2, 3]).

- 2D Tensor: a matrix (a table of numbers with rows and columns).

- 3D+ Tensors: data with more dimensions (like a color image with Height, Width, and Color Channels).

While similar to NumPy arrays, tensors are specifically designed to support automatic differentiation and GPU acceleration.

- Automatic differentiation works like a smart calculator that remembers every math step performed during a computation. As tensors go through operations such as addition or multiplication, PyTorch keeps track of how each result was produced. Later, when training a neural network, PyTorch goes backward through these recorded steps to figure out how much each tensor contributed to the final result. These contributions, called gradients, are automatically calculated and stored in the tensor’s `.grad` field, so the model knows how to adjust its parameters to improve performance.

- Deep learning involves millions of small mathematical operations, such as multiplying numbers together. Without a GPU (Graphics Processing Unit), the CPU (Central Processing Unit) must handle these computations alone. Although modern CPUs are fast, processing millions of operations still takes considerable time. GPUs are specifically designed to perform many of these small computations simultaneously. As a result, a task that might take a CPU an hour could be completed by a GPU in just a few seconds.

### Creation

The following functions are used to initialize tensors from scratch or existing data.

- `torch.tensor()`: creates a tensor from data (like a list, tuple or NumPy array).

In [19]:
import torch

data = [[1, 2, 3], [4.2, 5 ,6]]

torch_data1 = torch.tensor(data) # from a list
print(torch_data1)
print(torch_data1.dtype) # get the data type of a tensor

tensor([[1.0000, 2.0000, 3.0000],
        [4.2000, 5.0000, 6.0000]])
torch.float32


In [20]:
import numpy as np

np_data = np.ones((2, 3))
torch_data2 = torch.tensor(np_data)
print(torch_data2)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


- Create with random or sequence values by `torch.zeros()`, `torch.ones()`, `torch.randn()`, `torch.arange()` or `torch.linspace()`.

In [22]:
shape = (3, 2)
torch.zeros(shape)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [23]:
torch.ones((1,3))

tensor([[1., 1., 1.]])

In [24]:
torch.randn((2,1)) # returns a tensor filled with random numbers from a normal distribution (mean 0, variance 1)

tensor([[ 1.2675],
        [-1.0771]])

In [25]:
torch.arange(2, 20, 2) # torch.arange(start, end(exclusive), step) returns a 1D tensor with a range of values

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
torch.linspace(2, 20, 3) # torch.linspace() torch.linspace(start, end(inclusive), steps) returns a 1D tensor of steps equally spaced points between start and end

tensor([ 2., 11., 20.])

```{note}
When converting a NumPy array to a PyTorch Tensor, PyTorch inherits NumPy’s default floating-point precision *float64*. However, it is better to use the data type *float32* in deep learning for faster computation. 
```

- Use the `.float()` method to cast a tensor to the float32 data type for later training.

In [40]:
x = torch.arange(10)
print(x.dtype)
y = x.float()
print(y.dtype)

torch.int64
torch.float32


### Shape manipulation

<hr>

PyTorch has many shape manipulation functions because deep learning models frequently require tensors to be reshaped, transposed, or expanded between layers with different input requirements.

- View the shape of a tensor: `.shape`, `.ndim`.

In [47]:
x = torch.ones((3,4)) 
x.shape # another function .size() return same result as .shape

torch.Size([3, 4])

In [48]:
x.ndim # get the dimension of a tensor

2

. Change the shape of a tensor: `torch.squeeze()`, `.unsqueeze()`, `.flatten()`.

`torch.squeeze()` is to squeeze a tensor by removing the dimensions of size 1. Its syntex is:

<table>   
    <tr style="border-top:solid; border-bottom:solid">
        <th colspan=2 style="text-align:center">
            torch.squeeze(input, dim=None)
        </th>
    </tr>
    <tr>
        <td style="text-align:left">input</td>
        <td style="text-align:left">The input tensor.</td>
    </tr>
    <tr style="border-bottom:solid">
        <td style="text-align:left">dim</td>
        <td style="text-align:left">Given dimensions to squeeze.</td>
    </tr>
</table>

In [49]:
x = torch.ones((2, 1, 3, 1, 4))
x.shape

torch.Size([2, 1, 3, 1, 4])

In [50]:
y = torch.squeeze(x) # remove all the dimensions of size 1
y.shape

torch.Size([2, 3, 4])

In [51]:
y = torch.squeeze(x, 0)
y.shape # the shape does not change as the 0 dimension is not size 1

torch.Size([2, 1, 3, 1, 4])

In [52]:
y = torch.squeeze(x, dim=(1, 2)) # squeeze the size 1 dimension among the given dimensions
y.shape

torch.Size([2, 3, 1, 4])

- `unsqueeze()` is used to add a new dimension of size 1 at the specified position to a tensor.

<table>   
    <tr style="border-top:solid; border-bottom:solid">
        <th colspan=2 style="text-align:center">
            torch.unsqueeze(input, dim)
        </th>
    </tr>
    <tr>
        <td style="text-align:left">input</td>
        <td style="text-align:left">The input tensor.</td>
    </tr>
    <tr style="border-bottom:solid">
        <td style="text-align:left">dim</td>
        <td style="text-align:left">Given dimensions to unsqueeze.</td>
    </tr>
</table>

In [53]:
x = torch.tensor([1, 2, 3])
print(x)
x.shape

tensor([1, 2, 3])


torch.Size([3])

In [54]:
y = torch.unsqueeze(x, 0)
print(y)
y.shape

tensor([[1, 2, 3]])


torch.Size([1, 3])

In [55]:
y = torch.unsqueeze(x, 1)
print(y)
y.shape

tensor([[1],
        [2],
        [3]])


torch.Size([3, 1])

- `torch.flattern()` is to reshape a tensor to be one-dimensional.

In [56]:
x = torch.tensor([[1, 2, 3], [5, 6, 7]])
print(x)
print(x.shape)
y = torch.flatten(x)
print(y.shape)
print(y)

tensor([[1, 2, 3],
        [5, 6, 7]])
torch.Size([2, 3])
torch.Size([6])
tensor([1, 2, 3, 5, 6, 7])


### Expansion

- `.repeat()` is to repeat a tensor along the specified dimensions.

In [44]:
x = torch.tensor([1, 2, 3])
x.repeat((2, 3))

tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3]])

- `torch.full()` is to creat a tensor of specified size with **one given value**.

<table>   
    <tr style="border-top:solid; border-bottom:solid">
        <th colspan=2 style="text-align:center">
            torch.full(size, fill_value)
        </th>
    </tr>
    <tr>
        <td style="text-align:left">size</td>
        <td style="text-align:left">A list, tuple, or torch.Size. The specified size of the output tensor.</td>
    </tr>
    <tr style="border-bottom:solid">
        <td style="text-align:left">fill_value</td>
        <td style="text-align:left">A scalar. The given value to fill the tensor with.</td>
    </tr>
</table>

In [46]:
a = 2.3
torch.full((3,4), a)

tensor([[2.3000, 2.3000, 2.3000, 2.3000],
        [2.3000, 2.3000, 2.3000, 2.3000],
        [2.3000, 2.3000, 2.3000, 2.3000]])